version: '3.9'

services:
  event-ticket-api-dev:
    container_name: event-ticket-api-dev
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: sh -c "until nc -z postgres 5432; do echo 'Waiting for PostgresSQL...'; sleep 2; done; npm run db-migrate && npm run start:dev"
    environment:
      NODE_ENV: development
      PORT: 3000
      RECAPTCHA_SECRET_KEY: secret

      DATABASE_URL: postgres://user:pass@postgres:5432/test_db
      REDIS_URL: redis://redis:6379
      SEAT_LOCK_EXPIRATION: 600

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: test_db
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - '6379:6379'

volumes:
  postgres-data:
  redis-data:
