// General Seats Data
export const generalSeatData = [
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 1,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 2,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 3,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 4,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 5,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 6,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 7,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 8,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 9,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 1,
    row_number: 10,
    seat_number: 10,
    status: 'available',
  },
]

// VIP Seats Data
export const vipSeatData = [
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 1,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 2,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 3,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 4,
    seat_number: 10,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 1,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 2,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 3,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 4,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 5,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 6,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 7,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 8,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 9,
    status: 'available',
  },
  {
    event_id: 1,
    ticket_type_id: 2,
    row_number: 5,
    seat_number: 10,
    status: 'available',
  },
]
